apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudops-api-servicemonitor
  namespace: apps
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: cloudops-api
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
