apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudops-api.yaml
  - cloudops-api-ingress.yaml
  - grafana-ingress.yaml
  - cloudops-api-servicemonitor.yaml
  - cloudops-dashboard.yaml
  - cloudops-dashboard-ingress.yaml
  - apps-networkpolicy.yaml
